using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using PasskeyAuth.Api.Domain.Entities;
using PasskeyAuth.Api.Infrastructure.Data;
using System.Text.Json;
using System.Text;

namespace PasskeyAuth.Api.Application.Services;

public class TwoFactorMethodService : ITwoFactorMethodService
{
    private readonly ApplicationDbContext _context;
    private readonly IMemoryCache _cache;
    private readonly ILogger<TwoFactorMethodService> _logger;
    private readonly ISmsService _smsService;
    private readonly IEmailService _emailService;
    private readonly IPushNotificationService _pushNotificationService;
    private readonly Random _random = new();

    public TwoFactorMethodService(
        ApplicationDbContext context,
        IMemoryCache cache,
        ILogger<TwoFactorMethodService> logger,
        ISmsService smsService,
        IEmailService emailService,
        IPushNotificationService pushNotificationService)
    {
        _context = context;
        _cache = cache;
        _logger = logger;
        _smsService = smsService;
        _emailService = emailService;
        _pushNotificationService = pushNotificationService;
    }

    public async Task<string> GenerateCodeAsync(Guid userId, TwoFactorMethodType methodType)
    {
        string code;
        string cacheKey;

        switch (methodType)
        {
            case TwoFactorMethodType.TOTP:
                // TOTP codes are generated by authenticator app, but we can generate a mock for display
                code = _random.Next(100000, 999999).ToString("D6");
                cacheKey = $"2fa:totp:{userId}:{code}";
                _cache.Set(cacheKey, true, TimeSpan.FromMinutes(5));
                break;

            case TwoFactorMethodType.SMS:
                code = _random.Next(100000, 999999).ToString("D6");
                cacheKey = $"2fa:sms:{userId}:{code}";
                _cache.Set(cacheKey, true, TimeSpan.FromMinutes(10));
                
                // Get phone number from method configuration
                var smsMethod = await _context.TwoFactorMethods
                    .FirstOrDefaultAsync(m => m.UserId == userId && m.MethodType == TwoFactorMethodType.SMS && m.IsEnabled);
                var phoneNumber = "+1234567890";
                if (smsMethod != null && !string.IsNullOrEmpty(smsMethod.Configuration))
                {
                    var config = JsonSerializer.Deserialize<Dictionary<string, string>>(smsMethod.Configuration);
                    phoneNumber = config?.GetValueOrDefault("phoneNumber") ?? phoneNumber;
                }
                
                // Use external SMS service (mock for tests)
                await _smsService.SendCodeAsync(phoneNumber, code);
                _cache.Set($"2fa:sms:display:{userId}", code, TimeSpan.FromMinutes(10));
                break;

            case TwoFactorMethodType.Email:
                code = _random.Next(100000, 999999).ToString("D6");
                cacheKey = $"2fa:email:{userId}:{code}";
                _cache.Set(cacheKey, true, TimeSpan.FromMinutes(10));
                
                // Get email from user
                var user = await _context.Users.FindAsync(userId);
                var email = user?.Email ?? "";
                if (string.IsNullOrEmpty(email))
                {
                    var emailMethod = await _context.TwoFactorMethods
                        .FirstOrDefaultAsync(m => m.UserId == userId && m.MethodType == TwoFactorMethodType.Email && m.IsEnabled);
                    if (emailMethod != null && !string.IsNullOrEmpty(emailMethod.Configuration))
                    {
                        var config = JsonSerializer.Deserialize<Dictionary<string, string>>(emailMethod.Configuration);
                        email = config?.GetValueOrDefault("email") ?? email;
                    }
                }
                
                // Use external Email service (mock for tests)
                await _emailService.SendCodeAsync(email, code);
                _cache.Set($"2fa:email:display:{userId}", code, TimeSpan.FromMinutes(10));
                break;

            case TwoFactorMethodType.Push:
                // Get device ID from method configuration
                var pushMethod = await _context.TwoFactorMethods
                    .FirstOrDefaultAsync(m => m.UserId == userId && m.MethodType == TwoFactorMethodType.Push && m.IsEnabled);
                var deviceId = "default-device";
                if (pushMethod != null && !string.IsNullOrEmpty(pushMethod.Configuration))
                {
                    var config = JsonSerializer.Deserialize<Dictionary<string, string>>(pushMethod.Configuration);
                    deviceId = config?.GetValueOrDefault("deviceId") ?? config?.GetValueOrDefault("deviceName") ?? deviceId;
                }
                
                // Use external Push Notification service (mock for tests)
                code = await _pushNotificationService.SendApprovalRequestAsync(deviceId, userId.ToString());
                cacheKey = $"2fa:push:{userId}:{code}";
                _cache.Set(cacheKey, true, TimeSpan.FromMinutes(5));
                _cache.Set($"2fa:push:display:{userId}", code, TimeSpan.FromMinutes(5));
                break;

            case TwoFactorMethodType.U2F:
                // U2F uses WebAuthn challenge, return challenge ID
                code = Guid.NewGuid().ToString();
                cacheKey = $"2fa:u2f:{userId}:{code}";
                _cache.Set(cacheKey, true, TimeSpan.FromMinutes(5));
                break;

            default:
                throw new ArgumentException($"Unsupported 2FA method: {methodType}");
        }

        // Update last used timestamp
        var method = await _context.TwoFactorMethods
            .FirstOrDefaultAsync(m => m.UserId == userId && m.MethodType == methodType && m.IsEnabled);
        
        if (method != null)
        {
            method.LastUsedAt = DateTime.UtcNow;
            await _context.SaveChangesAsync();
        }

        return code;
    }

    public async Task<bool> VerifyCodeAsync(Guid userId, TwoFactorMethodType methodType, string code)
    {
        string cacheKey;

        switch (methodType)
        {
            case TwoFactorMethodType.TOTP:
                cacheKey = $"2fa:totp:{userId}:{code}";
                break;
            case TwoFactorMethodType.SMS:
                cacheKey = $"2fa:sms:{userId}:{code}";
                break;
            case TwoFactorMethodType.Email:
                cacheKey = $"2fa:email:{userId}:{code}";
                break;
            case TwoFactorMethodType.Push:
                cacheKey = $"2fa:push:{userId}:{code}";
                break;
            case TwoFactorMethodType.U2F:
                // U2F verification is handled separately via WebAuthn
                return false;
            default:
                return false;
        }

        if (_cache.TryGetValue(cacheKey, out _))
        {
            _cache.Remove(cacheKey);
            return true;
        }

        return false;
    }

    public async Task<object> SetupMethodAsync(Guid userId, TwoFactorMethodType methodType, Dictionary<string, string>? configuration = null)
    {
        // Check if user has any primary method
        var hasPrimary = await _context.TwoFactorMethods
            .AnyAsync(m => m.UserId == userId && m.IsPrimary);
        
        var method = new TwoFactorMethod
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            MethodType = methodType,
            IsEnabled = true,
            IsPrimary = !hasPrimary, // Set as primary if user has no primary method
            Configuration = configuration != null ? JsonSerializer.Serialize(configuration) : null,
            CreatedAt = DateTime.UtcNow
        };

        _context.TwoFactorMethods.Add(method);
        await _context.SaveChangesAsync();

        // Generate setup data based on method type
        object setupData = methodType switch
        {
            TwoFactorMethodType.SMS => new
            {
                phoneNumber = configuration?.GetValueOrDefault("phoneNumber") ?? "+1234567890",
                message = "SMS code will be displayed on screen (mock)"
            },
            TwoFactorMethodType.Email => new
            {
                email = configuration?.GetValueOrDefault("email") ?? "",
                message = "Email code will be displayed on screen (mock)"
            },
            TwoFactorMethodType.Push => new
            {
                deviceName = configuration?.GetValueOrDefault("deviceName") ?? "Mobile Device",
                message = "Push notification will be simulated (mock)"
            },
            TwoFactorMethodType.U2F => new
            {
                message = "Use your security key (YubiKey, etc.)",
                challenge = Convert.ToBase64String(Encoding.UTF8.GetBytes(Guid.NewGuid().ToString()))
            },
            _ => new { message = "Setup complete" }
        };

        return new
        {
            methodId = method.Id,
            methodType = methodType.ToString(),
            setupData = setupData
        };
    }

    public async Task<List<TwoFactorMethod>> GetUserMethodsAsync(Guid userId)
    {
        return await _context.TwoFactorMethods
            .Where(m => m.UserId == userId)
            .OrderByDescending(m => m.IsPrimary)
            .ThenByDescending(m => m.LastUsedAt)
            .ToListAsync();
    }

    public async Task SetPrimaryMethodAsync(Guid userId, Guid methodId)
    {
        var methods = await _context.TwoFactorMethods
            .Where(m => m.UserId == userId)
            .ToListAsync();

        foreach (var method in methods)
        {
            method.IsPrimary = method.Id == methodId;
        }

        await _context.SaveChangesAsync();
    }

    public async Task DisableMethodAsync(Guid userId, Guid methodId)
    {
        var method = await _context.TwoFactorMethods
            .FirstOrDefaultAsync(m => m.Id == methodId && m.UserId == userId);

        if (method != null)
        {
            method.IsEnabled = false;
            await _context.SaveChangesAsync();
        }
    }
}

